package frc.robot.subsystems;

import edu.wpi.first.wpilibj2.command.SubsystemBase;
import org.littletonrobotics.junction.Logger;
import org.littletonrobotics.junction.inputs.LoggableInputs;

/**
 * A subsystem dedicated to managing the logging of other subsystems.
 * It utilizes a time-slicing approach to distribute the logging overhead
 * across multiple loop cycles, preventing CPU spikes.
 */
public class LoggingSubsystem extends SubsystemBase {

    private LoggedSubsystem[] subsystems;
    private int timer;

    // Determines how many cycles to spread the logging over.
    // e.g., if oftenness is 2, half the subsystems log on even cycles, half on odd.
    private final int oftenness = 2;

    /**
     * Creates a new LoggingSubsystem.
     *
     * @param subsystems A varargs list of subsystems that implement the LoggedSubsystem interface.
     */
    public LoggingSubsystem(LoggedSubsystem... subsystems) {
        this.subsystems = subsystems;
    }

    @Override
    public void periodic() {
        // Increment timer and wrap around based on 'oftenness'
        timer++;
        timer %= oftenness;

        // Iterate through the subsystems, but only process a subset based on the current timer.
        // This loop starts at the current 'timer' index and skips by 'oftenness'.
        for (int i = timer; i < subsystems.length; i += oftenness) {
            String name = subsystems[i].getNameLog();
            // Process inputs for AdvantageKit logging
            Logger.processInputs(name, subsystems[i].log());
        }
    }

    /**
     * Interface to be implemented by any subsystem that wants to be managed by LoggingSubsystem.
     */
    public static interface LoggedSubsystem {

        /**
         * Returns the inputs object containing the data to be logged.
         * This is typically an AutoLog inputs class generated by AdvantageKit.
         *
         * @return The LoggableInputs object.
         */
        public LoggableInputs log();

        /**
         * Returns the name to use for the log table.
         * Defaults to the simple class name of the subsystem.
         *
         * @return The name of the subsystem for logging purposes.
         */
        public default String getNameLog() {
            return getClass().getSimpleName();
        }
    }
}
